### ISSUE TITLE
uptimeMillis() fails in JS tests

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#103]
`ReferenceError: window is not defined`. Should use `Date.now()`.

**Comment by lukaville** [comment]
I think we should use `window.performance.now()` in browsers and `process.hrtime()` in Node https://nodejs.org/api/process.html#process_process_hrtime_time

**Comment by arkivanov** [comment]
Please check the linked issue, it does not work in tests. What you mean by "monotonic"?

**Comment by lukaville** [comment]
@arkivanov I mean it may not increase monotonically (for example it can jump from `100` to `95`)
