### ISSUE TITLE
iOS Sample app broken/missing imports

### ISSUE THREAD

**Issue by kuhnroyal** [badoo/Reaktive#111]
The ios-simple-app doesn't compile in Xcode, somehow `ReaktiveSingleObserver` as well as those for `Observable` and `Maybe` are not available in Swift/XCode. Locking at the generated framework, only `ReaktiveObserver` is available but it does not have a `onSuccess/Error` methods. This causes the example to either fail or sometimes crash with `TypeInfo.cpp:41: runtime assert: Unknown open method` .

I created multiple sample projects with the released `1.0.0-beta1` artifacts and with the  generated framework directly built from the repository, both have this problem.

The required interfaces exist in the `com.badoo.reaktive:reaktive-iossim:klib:1.0.0-beta1` artifact, they are just not exported to the framework.

The required `KotlinThrowable` for the `onError` callback is also not available.

**Comment by arkivanov** [comment]
Thanks for reporting! We'll check.

**Comment by CherryPerry** [comment]
@kuhnroyal You can apply changes from https://github.com/badoo/Reaktive/pull/118 if you do not want to wait.

**Comment by kuhnroyal** [comment]
Thanks! This works with the current version in any project, just needs to be configured correctly.

The extension functions which are nice for Kotlin make it impossible to chain calls in Swift.

**Comment by CherryPerry** [comment]
@kuhnroyal We aware of the problem with extension functions on Swift, hope that it will be fixed in future releases. But for now we recommend to write all RX chains inside Kotlin module and use only observers in Swift (like in iOS sample).
