### ISSUE TITLE
Kotlin 1.3.40

### ISSUE THREAD

**Issue by CherryPerry** [badoo/Reaktive#123]
#### Plan
- [ ] Split `js` to `node` and `browser`, remove check in `uptime()` function.
- [ ] Use default `jsTest` instead of custom `mocha` run task.
- [x] ~~Use `FreezableAtomicReference` where it is possible (need to investigate @arkivanov).~~
- [ ] Enable `-Xobjc-generics` for iOS sample to check `Swift` generics support.
- [ ] Use new `test` binaries configuration for native platform.

[Read more](https://blog.jetbrains.com/kotlin/2019/06/kotlin-1-3-40-released/)

**Comment by arkivanov** [comment]
FreezableAtomicReference is experimental, looks like. And why do we need it overall?

**Comment by CherryPerry** [comment]
Ok, let's skip it.

**Comment by CherryPerry** [comment]
PR: https://github.com/badoo/Reaktive/pull/171
