### ISSUE TITLE
Gradle error: Unable to resolve dependency

### ISSUE THREAD

**Issue by OlexandrStepanov** [badoo/Reaktive#124]
Hello 👋,

I am trying to import reaktive dependency using gradle for kotlin-multiplatform project with Android and iOS targets, but get an error on gradle sync:

`ERROR: Unable to resolve dependency for ':common@debug/compileClasspath': Could not resolve com.badoo.reaktive:reaktive-android:1.0.0-beta1.`

The project I'm adding this library is here:
https://github.com/OlexandrStepanov/Kotlin-Native-MVP-Demo/tree/reaktive-experiments

The files with this dependency added:
- Link to Badoo Maven repo: https://github.com/OlexandrStepanov/Kotlin-Native-MVP-Demo/blob/reaktive-experiments/build.gradle
- Common module build.gradle: https://github.com/OlexandrStepanov/Kotlin-Native-MVP-Demo/blob/reaktive-experiments/common/build.gradle

All changes in the project, which lead to this error in a single commit:
https://github.com/OlexandrStepanov/Kotlin-Native-MVP-Demo/commit/a43e751c2da465aa235af8f763368751c5447bd2

Please, suggest, what I'm doing wrong.
With regards.

**Comment by arkivanov** [comment]
Hello, please update your Gradle wrapper to at least 5.3 (I have just checked it using 5.4.1). Reaktive is published using metadata mode so you should normally specify dependency _only in common source set_. Others should be resolved automatically. You can read more about it [here](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#experimental-metadata-publishing-mode).

**Comment by OlexandrStepanov** [comment]
Thank you, @arkivanov, your suggestion did fix the issue.

**Comment by tassilo-posegga** [comment]
Same issue with gradle 6.5.1
