### ISSUE TITLE
InvalidMutabilityException in subscribe closure

### ISSUE THREAD

**Issue by OlexandrStepanov** [badoo/Reaktive#129]
Hello there 👋,

I have faced with an issue, that when using `this` in `onNext` closure of `subscribe` method, it got frozen along with all properties subgraph, which raise `InvalidMutabilityException` exception on any mutation of that properties.
Looking at issue #72, I see that this is expected behaviour on K/N.
But at the same time, restriction to have non-mutating logic in `onNext` closure is too bold for me, and makes this framework usage senseless.
I guess there must be some workaround for this problem, just can't figure it out.

The sample project I'm playing with is here:
https://github.com/OlexandrStepanov/Kotlin-Native-MVP-Demo/tree/reaktive-experiments

The file with logic I'm talking about is SearchViewModel.kt, lines 45:48. Uncommenting `reload(it)` call cause next crash in iOS app on runtime:
```
Uncaught Kotlin exception: kotlin.native.concurrent.InvalidMutabilityException: mutation attempt of frozen com.akqa.kn.lib.LocationServiceImpl@24ed568
```

According to the logic in that class, I need to mutate `this` in `onNext` callback of `subscribe`.
Could you, please, suggest, how could I achieve this?

With regards.

**Comment by arkivanov** [comment]
Hello, unfortunately this is how Kotlin Native memory model is designed. It's not allowed to mutate shared state from different threads. In your example your are accessing `LocationServiceImpl` from `onNext` callback which might be called from any thread, there is no way to avoid freezing here.

You should rethink how you are writing the code. You should use immutable objects (collections, data classes, etc.) and atomic references (there is `AtomicReference` that is already available from Reaktive library, and `AtomicInt`, `AtomicLong` and `AtomicBoolean` will be available with the next release).

Consider the following example:
```
class MyClass {
    private val list = AtomicReference<List<String>>(emptyList())

    fun foo() {
        observableOf("1")
            .subscribeOn(computationScheduler)
            .subscribe(
                onNext = { value ->
                    list.update { it + value }
                }
            )
    }
}
```

Also I see you are using coroutines, they are single threaded at the moment and I can't predict how they will behave in a multi-threaded environment.

**Comment by arkivanov** [comment]
There is an open discussion about multithreading in coroutines: https://github.com/Kotlin/kotlinx.coroutines/issues/462

**Comment by arkivanov** [comment]
Closing the issue due to inactivity, feel free to reopen or create a new one if it is still relevant. Thanks!
