### ISSUE TITLE
Why is this library a android project?

### ISSUE THREAD

**Issue by yangwuan55** [badoo/Reaktive#13]
I think this library should be a kotlin native project.All of the kotlin project can use this.But now
it's a android library,why don't I use RxKotlin?

**Comment by arkivanov** [comment]
The library is Kotlin Multiplatform project with Android Sample app. We will add iOS target and sample app soon. Checkout official MPP example: https://github.com/JetBrains/kotlin-mpp-example

**Comment by arkivanov** [comment]
And more targets will be added later

**Comment by yangwuan55** [comment]
Looking forward 💯
