### ISSUE TITLE
Handle exceptions in doOn*** methods

### ISSUE THREAD

**Issue by diklimchuk** [badoo/Reaktive#137]
Currently exceptions thrown in doOn*** methods are not handled at all.
Sample test:
```
    @Test
    fun testErrorIsPropagated() {
        val observer = singleOf(1)
            .doOnBeforeSuccess { throw Exception("Simulated error") }
            .test()
        assertTrue(observer.isError)
    }
```
RxJava in case of exceptions in such methods proceeds with onError, so it would be great if Reaktive could support that behaviour

**Comment by arkivanov** [comment]
Hey @diklimchuk, thanks for the report, I'll fix it. Btw, you can use extension function `observer.assertError(...)`.

**Comment by diklimchuk** [comment]
Great! Thank for the note as well.
