### ISSUE TITLE
Consider klock dependency.

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#151]
@mk-jones @lukaville @CherryPerry Guys let's decide whether we need 'klock' library or not. It has nice [https://github.com/korlibs/klock/blob/master/klock/src/commonMain/kotlin/com/soywiz/klock/TimeSpan.kt](TimeSpan). Also perhaps we could remove our expect/actual 'uptimeMills'. We need to decide before release.
Other contributors are also welcome to discuss.

**Comment by dmitryustimov** [comment]
Isn't it be better to copy few `klock` classes to the `com.badoo.reaktive.utils.time` package instead of making `Reactive` dependent on external library?
`klock` code is dual licensed under MIT and Apache 2.0 and we can mention the author.
But I'm not so familiar with possible legal issues.

**Comment by arkivanov** [comment]
One more thing, if depend then Reaktive's Kotlin version must be same as in klock, to be able to build K/N part.

**Comment by arkivanov** [comment]
I'm for copying a few classes.

**Comment by arkivanov** [comment]
But if we copy then clients will see both variants if they are using ktor as well.

**Comment by CherryPerry** [comment]
Copy few classes into `com.badoo.reaktive.utils.time`.
For now, when native and metadata are not stable yet, we can get situation, when external dependency will use different version of metadata or Kotlin and we will be blocked by it.

> But if we copy then clients will see both variants if they are using klock as well.
Both variants of 2-3 classes? With different packages? Not a big deal.

**Comment by dmitryustimov** [comment]
FYI Kotlin 1.3.50 will offer us experimental date-time classes in standard library 
https://github.com/Kotlin/KEEP/blob/durations/proposals/stdlib/durations-and-clocks.md

**Comment by arkivanov** [comment]
> FYI Kotlin 1.3.50 will offer us experimental date-time classes in standard library
> https://github.com/Kotlin/KEEP/blob/durations/proposals/stdlib/durations-and-clocks.md

We want to release stable version very soon, changing public API without any critical reason will not be possible.

**Comment by arkivanov** [comment]
@lukaville @mk-jones What do you think guys?

**Comment by arkivanov** [comment]
I would better wait for Kotlin 1.3.50 with its `Duration` in stdlib. But it will block our release... Should we release RC1? And then stable version with `Duration` and Kotlin 1.3.50?

**Comment by arkivanov** [comment]
Closing the issue due to inactivity, looks like not relevant anymore. Feel free to reopen if needed.
