### ISSUE TITLE
Retrofit adapter

### ISSUE THREAD

**Issue by AlexeyKorshun** [badoo/Reaktive#203]
Where do you think it would be better to put the adapter for retrofit, in this repository or in theirs?

**Comment by CherryPerry** [comment]
I don't think they will accept this adapter.
And I am not sure about adding it here. We don't use Retrofit, so I think this adapter will become unmaintained in the nearest future.

If you need this adapter, you can host it on your account, and we will mention you in readme.

@arkivanov What do you think?

**Comment by arkivanov** [comment]
I would try adding it to Retrofit repo. If rejected then add it here. The feature is nice to have anyway.

**Comment by arkivanov** [comment]
Are there any news?

**Comment by AlexeyKorshun** [comment]
@arkivanov at the moment there is no news. I try to create PR to square repository in next weekends.

**Comment by AlexeyKorshun** [comment]
@arkivanov I asked them about it, because  their repository doesn't contain Kotlin and doesn't contain coroutines adapter. I think it may be a reason.

**Comment by AlexeyKorshun** [comment]
Jake didn't appreciate the idea. [issue](https://github.com/square/retrofit/issues/3227)

**Comment by AlexeyKorshun** [comment]
i have a trouble with using reaktive module in java module. I have warning 'java module can't use android dependency" and i can to create test. do you know how to fix this problem?

**Comment by arkivanov** [comment]
Could you please show your build.gradle or pom.xml ?

**Comment by arkivanov** [comment]
Try to specify the dependency as implementation project(':reaktive-jvm')

**Comment by AlexeyKorshun** [comment]
> Try to specify the dependency as implementation project(':reaktive-jvm')

it don't help 
`Project with path ':reaktive-jvm' could not be found`
I understand this warning isn't important. But when I execute a test it says that can't resolve dependancy from reaktive module.

**Comment by AlexeyKorshun** [comment]
I will try to resolve dependency from maven, but I m not sure that is great.

**Comment by arkivanov** [comment]
I deleted my comment as it

> > Try to specify the dependency as implementation project(':reaktive-jvm')
> 
> it don't help
> `Project with path ':reaktive-jvm' could not be found`
> I understand this warning isn't important. But when I execute a test it says that can't resolve dependancy from reaktive module.

The warning itself is not important and it works for rxjava interop modules. Tests are also fine. Please double check that everything is same.

**Comment by arkivanov** [comment]
Dependency should be specified as `project('reaktive')`, sorry for confusions

**Comment by arkivanov** [comment]
Feel free to post any errors you have, I'm here to help.
