### ISSUE TITLE
Add new line at the end of files to all kotlin files

### ISSUE THREAD

**Issue by CherryPerry** [badoo/Reaktive#235]
To support detekt's NewLineAtEndOfFile rule and make diffs more clear.
Do after https://github.com/badoo/Reaktive/pull/227 is merged. Do not forget to enable rule back in `detekt.yml`.

**Comment by mayokunthefirst** [comment]
Hello, I'll love to jump on this..

**Comment by arkivanov** [comment]
@mayokunthefirst hello, you are very welcome
