### ISSUE TITLE
Upgrade to Kotlin 1.3.60

### ISSUE THREAD

**Issue by minaEweida** [badoo/Reaktive#303]
Hi, Are there plans to upgrade Kotlin 1.3.6 soon?

**Comment by arkivanov** [comment]
Hey, sure, will do it today!

**Comment by minaEweida** [comment]
Thanks, I just tried upgrading now just to test out but it seems coroutines version is not working due to different abi version

**Comment by arkivanov** [comment]
Yeah, Coroutines prevent Reaktive from being updated. We need to wait.

**Comment by arkivanov** [comment]
The new version `1.1.1` should be [published](https://github.com/badoo/Reaktive/commit/9a5f2842fe0cb8fce24b360d93c6e6528f79dc39/checks?check_suite_id=322404056) soon
