### ISSUE TITLE
Support multithreaded coroutines for Kotlin/Native in coroutines-interop

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#304]
Currently `corotuines-interop` is implemented differently for Kotlin/Native, using `runBlocking`. This is because Job can not be frozen. It has one significant limitation - you can't use `coroutines-interop` on main thread and `subscribeOn` is required. Looks like after https://github.com/Kotlin/kotlinx.coroutines/pull/1648 it will be fixed and we will be able to use same implementation as for JVM.

**Comment by arkivanov** [comment]
#314 seems working with mt coroutines version. We could make a separate branch for mt coroutines interop as well, and publish. Perhaps publication of only `coroutines-interop` module would be enough. 

Is there a demand?

@CherryPerry JFYI

**Comment by nectar1** [comment]
Cool news. Lets do separate branch 
![image](https://user-images.githubusercontent.com/5610837/90115151-6043b080-dd5c-11ea-9944-7e0a6a7e436d.png)

**Comment by arkivanov** [comment]
Multi-threaded coroutines interop is published with `-nmtc` version suffix. Please see the corresponding [Readme section](https://github.com/badoo/Reaktive#coroutines-interop) for more information.
