### ISSUE TITLE
Equivalent of RxJava's ObservablePublishSelector?

### ISSUE THREAD

**Issue by saket** [badoo/Reaktive#315]
RxJava has a nifty operator variant of `publish(Function)` that offers a scoped way to consume published events, removing the requirement of manually calling `connect()`. 

```kotlin
Observable.just("value")
  .publish { publishedEvents -> 
    // connect() is called when merge() subscribes.
    merge(consumerA(publishedEvents), consumerB(publishedEvents)
  }
```

Is it possible to write a similar operator by using the existing operators in Reaktive? Or would that require a custom operator?

**Comment by arkivanov** [comment]
Hey, I need to think about it

**Comment by saket** [comment]
I came up with this. What do you think?

```kotlin
fun <T, R> Observable<T>.publishElements(block: (Observable<T>) -> Observable<R>): Observable<R> {
  val published = publish()
  return block(published).doOnAfterSubscribe {
    published.connect()
  }
}

fun <T> Observable<T>.doOnAfterSubscribe(action: (Disposable) -> Unit): Observable<T> =
  observableUnsafe { observer ->
    val disposableWrapper = DisposableWrapper()
    observer.onSubscribe(disposableWrapper)

    subscribe(
        object : ObservableObserver<T>, ValueCallback<T> by observer {
          override fun onSubscribe(disposable: Disposable) {
            disposableWrapper.set(disposable)
          }

          override fun onComplete() {
            disposableWrapper.doIfNotDisposed(dispose = true, block = observer::onComplete)
          }

          override fun onError(error: Throwable) {
            disposableWrapper.doIfNotDisposed(dispose = true) {
              observer.onError(error)
            }
          }
        }
    )

    try {
      action(disposableWrapper)
    } catch (e: Throwable) {
      observer.onError(e)
      disposableWrapper.dispose()
    }
  }
```

**Comment by arkivanov** [comment]
I still did not have chance to poke this, sorry. I will definitely do this soon. As of your implementation I think it is a bit wrong. AFAIK `publish()` should should be per subscription, not per instance.

**Comment by arkivanov** [comment]
And a question, do you really need `publish(selector)` operator now? Given we will have `autoConnect` and `replay(bufferSize)` in the next release?

**Comment by saket** [comment]
Yes, `autoConnect()` has a different effect on the stream. Here's an example.

```kotlin
val upstream = observableFromFunction { expensiveWork() }
val sharedUpstream = upstream.share()

sharedUpstream
  .take(1)
  .subscribe { ... }

sharedUpstream
  .take(1)
  .subscribe { ... }
```

In this example, `upstream` will be subscribed twice, resulting in `expensiveDoWork` being performed twice because `refCount()` will see the subscriber count go from 0 -> 1 -> 0 -> 1 -> 0.

`publishElements()` helps avoid this problem by only connecting upstream once all inner streams have been subscribed.

In comparison, `autoConnect()` will start the stream right away even when there's no one listening. It'll also not get disconnected when the subscribers stop listening.

**Comment by saket** [comment]
> As of your implementation I think it is a bit wrong. AFAIK publish() should should be per subscription, not per instance.

I wrote this piece of code to check the behavior. Is there something I'm missing?

```kotlin
val events = observableOf(Unit).doOnBeforeSubscribe { println("Shared stream subscribed") }

events
    .publishElements { sharedEvents ->
      merge(
          sharedEvents.map { "First" }.doOnBeforeSubscribe { println("First consumer subscribed") },
          sharedEvents.map { "Second" }.doOnBeforeSubscribe { println("Second consumer subscribed") }
      )
    }
    .subscribe { println("$it received") }
```

Output:
```
First consumer subscribed
Second consumer subscribed
Shared stream subscribed
First received
Second received
```

**Comment by arkivanov** [comment]
What is `publishElements` in your example?

**Comment by saket** [comment]
It's the function I mentioned in my comment above: https://github.com/badoo/Reaktive/issues/315#issuecomment-561784734

**Comment by arkivanov** [comment]
> > As of your implementation I think it is a bit wrong. AFAIK publish() should should be per subscription, not per instance.
> 
> I wrote this piece of code to check the behavior. Is there something I'm missing?
> 
> ```kotlin
> val events = observableOf(Unit).doOnBeforeSubscribe { println("Shared stream subscribed") }
> 
> events
>     .publishElements { sharedEvents ->
>       merge(
>           sharedEvents.map { "First" }.doOnBeforeSubscribe { println("First consumer subscribed") },
>           sharedEvents.map { "Second" }.doOnBeforeSubscribe { println("Second consumer subscribed") }
>       )
>     }
>     .subscribe { println("$it received") }
> ```
> 
> Output:
> 
> ```
> First consumer subscribed
> Second consumer subscribed
> Shared stream subscribed
> First received
> Second received
> ```

The original publish with selector will re-subscribe if you call `.subscribe { println("$it received") }` second time. However your implementation will not.

**Comment by arkivanov** [comment]
> And a question, do you really need `publish(selector)` operator now? Given we will have `autoConnect` and `replay(bufferSize)` in the next release?

Alright, just naming is different, RxJava does not have this AFAIK

**Comment by arkivanov** [comment]
Alright I understood your use case. I will think a bit more and probably just implement it. Thanks!

**Comment by saket** [comment]
> The original publish with selector will re-subscribe if you call .subscribe { println("$it received") } second time. However your implementation will not.

Hmm, `publish()` is called everytime `publishElements` is called so I'm not sure if that's true. Does this look correct to you?

```kotlin
val events = observableOf(Unit).doOnBeforeSubscribe { println("Shared stream subscribed") }

events
    .publishElements { sharedEvents ->
      merge(
          sharedEvents.map { "First" }.doOnBeforeSubscribe { println("First consumer subscribed") },
          sharedEvents.map { "Second" }.doOnBeforeSubscribe { println("Second consumer subscribed") }
      )
    }
    .subscribe { println("$it received") }

events
    .publishElements { sharedEvents ->
      merge(
          sharedEvents.map { "Third" }.doOnBeforeSubscribe { println("Third consumer subscribed") },
          sharedEvents.map { "Fourth" }.doOnBeforeSubscribe { println("Fourth consumer subscribed") }
      )
    }
    .subscribe { println("$it received") }
```

Output:
```
First consumer subscribed
Second consumer subscribed
Shared stream subscribed
First received
Second received

Third consumer subscribed
Fourth consumer subscribed
Shared stream subscribed
Third received
Fourth received
```

> Alright, just naming is different, RxJava does not have this AFAIK

I'm sorry I don't follow. Which operator are you referring to that's not available on RxJava?

**Comment by arkivanov** [comment]
> > The original publish with selector will re-subscribe if you call .subscribe { println("$it received") } second time. However your implementation will not.
> 
> Hmm, `publish()` is called everytime `publishElements` is called so I'm not sure if that's true. Does this look correct to you?
> 
> ```kotlin
> val events = observableOf(Unit).doOnBeforeSubscribe { println("Shared stream subscribed") }
> 
> events
>     .publishElements { sharedEvents ->
>       merge(
>           sharedEvents.map { "First" }.doOnBeforeSubscribe { println("First consumer subscribed") },
>           sharedEvents.map { "Second" }.doOnBeforeSubscribe { println("Second consumer subscribed") }
>       )
>     }
>     .subscribe { println("$it received") }
> 
> events
>     .publishElements { sharedEvents ->
>       merge(
>           sharedEvents.map { "Third" }.doOnBeforeSubscribe { println("Third consumer subscribed") },
>           sharedEvents.map { "Fourth" }.doOnBeforeSubscribe { println("Fourth consumer subscribed") }
>       )
>     }
>     .subscribe { println("$it received") }
> ```
> 
> Output:
> 
> ```
> First consumer subscribed
> Second consumer subscribed
> Shared stream subscribed
> First received
> Second received
> 
> Third consumer subscribed
> Fourth consumer subscribed
> Shared stream subscribed
> Third received
> Fourth received
> ```
> 
> > Alright, just naming is different, RxJava does not have this AFAIK
> 
> I'm sorry I don't follow. Which operator are you referring to that's not available on RxJava?

I don't have my computer handy but what I mean is publish should be called for every subscription, not for every operator call. This is how I understand RxJava implementation.

**Comment by arkivanov** [comment]
So
```
val publish = events.piblish {...}
publish.subsribe()
publish.subsribe()
```

I this case `events` should be subscribed twice. This is how I understand RxJava's implementation so far.

**Comment by saket** [comment]
> I don't have my computer handy but what I mean is publish should be called for every subscription, not for every operator call. This is how I understand RxJava implementation.

Right I see what you mean.
