### ISSUE TITLE
Make it easy to write custom operators

### ISSUE THREAD

**Issue by saket** [badoo/Reaktive#317]
Not sure if this is something you want to consider at this stage, but will it be possible to expose safer classes that can be used for writing custom operators? I sometimes find it difficult to write operators along the lines of the existing ones because they (e.g., `replay()`) make heavy usage of internal classes.

**Comment by arkivanov** [comment]
I completely understand your point. The stuff is internal for a reason: we need flexibility. E.g. we can modify or even remove the internal `publish(subjectFactory: () -> Subject<T>)` function and we don't need to care about binary compatibility in this case. 

So you have two options:
1. copy-paste the code you need into your project under original package name: `com.badoo.reaktive` (e.g. we created `ReaktiveUtils` module where all this stuff lives)
2. if you think something worth exposing, then ask us for a particular things (e.g. recently we exposed `ErrorCallback.tryCatch` functions)

**Comment by saket** [comment]
Fair point. Option 1 sounds like a decent workaround until then, thank you!
