### ISSUE TITLE
Publish snapshot version

### ISSUE THREAD

**Issue by CherryPerry** [badoo/Reaktive#322]
~~Use GitHub package manager~~ GitHub package manager [does not](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-apache-maven-for-use-with-github-packages) support maven's snapshots.

**Comment by CherryPerry** [comment]
@arkivanov 
Can we use sonatype for snapshot publishing now?
Do we need some additional steps in registration process to do it?

**Comment by arkivanov** [comment]
@CherryPerry I think we can, and no additional privileges should be required.
