### ISSUE TITLE
When adding reaktive dependecy, some permissions are merged into final apk maniphest

### ISSUE THREAD

**Issue by mikezliu** [badoo/Reaktive#334]
When I add this line:

commonMain.dependencies {
            implementation 'com.badoo.reaktive:reaktive:1.1.4'
            ...
}

My final APK has 3 extra permissions (WRITE_EXTERNAL_STORAGE, READ_PHONE_STATE, WAKE_LOCK). When looking into the merge blame file, it says this:

16    < uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
17    < uses-permission android:name="android.permission.READ_PHONE_STATE" />
18    < uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
19    < uses-permission android:name="android.permission.WAKE_LOCK" /> 
19-->[com.google.android.gms:play-services-measurement-api:17.2.1]

When I remove the line 'implementation 'com.badoo.reaktive:reaktive:1.1.4'', my final merged apk doesn't have these 3 permissions. Any idea what's going on?

**Comment by arkivanov** [comment]
Thanks for reporting the issue! Looks like it is because `Reaktive` has `minSdkVersion 1`. I will fix this.
