### ISSUE TITLE
Upgrade to Android SDK 29

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#336]
- Bump `buildToolsVersion`, `compileSdkVersion` and `targetSdkVersion`
- Migrate sample app to androidx

**Comment by arkivanov** [comment]
Do after #335

**Comment by mayokunthefirst** [comment]
@arkivanov Would love to help get this done.

**Comment by arkivanov** [comment]
@mayokunthefirst Thanks, assigned to you
