### ISSUE TITLE
Vote: Channel in Slack

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#364]
Do we need it? Please react with 👍👎. Thanks!

**Comment by saket** [comment]
Which slack is this?

**Comment by arkivanov** [comment]
> Which slack is this?

I would create #reaktive channel in Kotlin Slack, looks like it is possible.

**Comment by saket** [comment]
Gotcha. Sounds useful to me!

**Comment by AlexeyKorshun** [comment]
Can it be a channel in Telegram?

**Comment by mikezliu** [comment]
A channel would be good! Doesn't matter where

**Comment by arkivanov** [comment]
> Can it be a channel in Telegram?

It can be, but I believe Kotlin Slack has greater audience. Correct me if I'm wrong.

**Comment by arkivanov** [comment]
Thanks all for voting! Create the channel: https://kotlinlang.slack.com/archives/CU05HB31A
