### ISSUE TITLE
Investigate Swift extensions

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#368]
Reaktive can be exposed to Swift because it is not based on coroutines. But calling its operators does not look nice. We need to investigate if we can provide Swift extensions.

**Comment by saket** [comment]
This would be amazing. I haven't yet started working on the iOS side of my multiplatform project but I regularly wonder what the bridge with reaktive code will look like.

**Comment by arkivanov** [comment]
> This would be amazing. I haven't yet started working on the iOS side of my multiplatform project but I regularly wonder what the bridge with reaktive code will look like.

Well, normally you don't need to expose Rx outside of MPP. Better to keep it internal and expose some sort of lifecycle callbacks which clients will call. But in rare cases you might need to expose. We'll think how to deal with this.

**Comment by arkivanov** [comment]
Appears to be impossible at the moment. According to https://github.com/JetBrains/kotlin-native/blob/master/OBJC_INTEROP.md#limitations

> Generics can only be defined on classes, not on interfaces (protocols in Objc and Swift) or functions.
