### ISSUE TITLE
Support Testing asserts chaining

### ISSUE THREAD

**Issue by Maragues** [badoo/Reaktive#385]
Chaining multiple test functions is currently not supported

```kotlin
val versions = versionsReader.read().test()
                .assertError()
                .value //won't compile because assertError returns Unit
```

This should be easy

```kotlin 
fun TestObserver.assertError() {
    assertTrue(isError, "Source did not fail")
}
```
to

```kotlin 
fun TestObserver.assertError() : TestObserver {
    assertTrue(isError, "Source did not fail")

    return this
}
```

And I don't think it'll break anyone's code

**Comment by arkivanov** [comment]
Thanks for the issue, we will consider this. From first point of view this breaks binary compatibility, but maybe it is acceptable for `testing` module. Till then you can write like this:
```
val versions = versionsReader.read().test().run {
                assertError()
                value
}
```

Plus perhaps it is better to split such a test for two, one asserting for error and another one verifying the value.
