### ISSUE TITLE
iOS sample code contains retain loop

### ISSUE THREAD

**Issue by johankool** [badoo/Reaktive#388]
The iOS sample code contains a retain loop. The [ViewController](https://github.com/badoo/Reaktive/blob/5ec83b4244e25783fc70b50b547212c12b40cefc/sample-ios-app/sample-ios-app/ViewController.swift) owns the KittenView and the KittenView owns the ViewController. Personally I am not very familiar with the used approach which is not entirely idiomatic for Swift/iOS so not entirely sure what the best fix would be.

**Comment by arkivanov** [comment]
Thanks for reporting the issue. We'll fix.

**Comment by AlexeyKorshun** [comment]
As I know it is a normal for iOS, but you should use 'weak' in KittenView for viewController.
