### ISSUE TITLE
Internal stuff is included into binary compatibility files for coroutines-interop module

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#409]
And maybe for some other modules?

**Comment by CherryPerry** [comment]
Samples?

**Comment by arkivanov** [comment]
> Samples?

Please see #410

**Comment by arkivanov** [comment]
Also this one: https://github.com/badoo/Reaktive/blob/4df66f96e8de00fe94d8661ef0b75152d5ac2d31/tools/binary-compatibility/reference-public-api/coroutines-interop.txt#L15
