### ISSUE TITLE
Single scheduler

### ISSUE THREAD

**Issue by kwasny2** [badoo/Reaktive#417]
Reaktive lacks support for single scheduler (rxjava have it). I need this to ensure some observed io operations are properly queued until single thread scheduler is ready to execute it. That operations cannot be done on typical main thread. That operations must be synchronous because my communication channel is very limited and i will not accept any new operation until previous one is not completed (with sucess or failure). I do not need freezing. I am using jvm(android). Any plan to implement such functionality? Good alternative will be also possiblity to configure io scheduler to use only one thread.

**Comment by arkivanov** [comment]
Hey, Reaktive has `singleScheduler`: https://github.com/badoo/Reaktive/blob/f890127851f699de1a1fef555dbb9921b836af6d/reaktive/src/commonMain/kotlin/com/badoo/reaktive/scheduler/Schedulers.kt#L53

Does it work for you?

**Comment by kwasny2** [comment]
Thank you, I have not found this in docs. I will try!

**Comment by arkivanov** [comment]
Thanks, I will update the Readme
