### ISSUE TITLE
Inconsistency in behavior of replay

### ISSUE THREAD

**Issue by yevkavaliou** [badoo/Reaktive#420]
Hey.

I wrote a test and run it on both RxJava and Reaktive and observed different results. Here is the test:

```
@Test
fun testReplayRefCount() {
    val subject = BehaviorSubject.createDefault(false)
    val sharedStream = subject.replay(1).refCount(1)

    var disposable = sharedStream.test()
    subject.onNext(true)

    disposable.assertValues(false, true)
    disposable.dispose()

    disposable = sharedStream.test()
    subject.onNext(false)

    disposable.assertValues(true, false)
}
```

As you might guess, running this test with RxJava results in green, while with Reaktive - red.
Looks like on second subscription, the internal implementation of replay creates a new [ReplaySubject](https://github.com/badoo/Reaktive/blob/master/reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Replay.kt#L11) which results in a situation where all subsequent `onNext` calls are happen for newly created instance and lost for an existing one.

**Comment by arkivanov** [comment]
Thanks for reporting the bug, I will fix!

**Comment by arkivanov** [comment]
Spend a few hours debugging this. According to RxJava java docs for `ConnectableObservable`:

> Disposing the connection will reset the {@code ConnectableFlowable} to its fresh state and there is no need to call {@code reset()} in this case.

This pretty much what Reaktive's implementation of `refCount` does. It just calls `disconnect` when amount of subscribers reaches 0. But RxJava's `ConnectableObservable` has additional `reset` method. And this method is called by `refCount` after `disconnect`.

According to docs there should not be any difference in this particular case, `ConnectableObservable` should reset in its initial state in both cases. So it looks like both RxJava's and Reaktive's implementations of `publish` and `replay` operators have a bug - `disconnect` does not reset.

I raised the following issue: https://github.com/ReactiveX/RxJava/issues/6920. We will see how it goes and will make the Reaktive implementation consistent with RxJava.

Thanks!

**Comment by arkivanov** [comment]
Status update: the related RxJava issue (https://github.com/ReactiveX/RxJava/issues/6920) is was fixed, now waiting for its release, after that I will make Reaktive consistent.

**Comment by arkivanov** [comment]
Status update: RxJava snapshot with the fix are available, will fix this bug soon

**Comment by yevkavaliou** [comment]
Glad to hear.
Frankly speaking, I haven't expected that this bug will have such consequences - we literally revealed a bug in RxJava itself :)

I appreciate your work, thank you!
