### ISSUE TITLE
Add flatMapLatest or switchLatest operator

### ISSUE THREAD

**Issue by dcvz** [badoo/Reaktive#431]
Some Rx implementations add these methods to help with transformations of only the most recent observable sequence.

It'd be really useful to have a similar implementation for Reaktive.

[rxjs](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/flatmaplatest.md) and RxSwift are examples.

**Comment by arkivanov** [comment]
Reaktive has `switchMap`, is it what you are looking for? http://reactivex.io/documentation/operators/flatmap.html

**Comment by arkivanov** [comment]
https://github.com/ReactiveX/RxJava/blob/fd496db9a64320fcb9f9b4d110018bcd41e46c82/src/main/java/io/reactivex/rxjava3/core/Observable.java#L13227

**Comment by dcvz** [comment]
It was! Thanks a lot @arkivanov 🎉 I guess I missed it while looking through the source files..
