### ISSUE TITLE
Bug in `scan` operator?

### ISSUE THREAD

**Issue by dcvz** [badoo/Reaktive#432]
Hi! First of all thanks for this library. It's been fun to use and extend :)

I was adding an operator that would allow me to have the previously emitted value: 

```kotlin
fun <T> Observable<T>.withPrevious(): Observable<Pair<T?, T>> {
     return scan(listOf<T>(), { previous, current ->
         (previous + current).takeLast(2)
     }).map { Pair(if (it.size > 1) it.first() else null, it.last()) }
}
```

However this was triggering an issue where I was accessing an empty array.. upon digging into the code, I realized that the lib is emitting the seed value. As far as I understand about Rx that shouldn't happen so I'm raising an issue in case I am wrong.

I solved it for now by skipping the first value:

```kotlin
fun <T> Observable<T>.withPrevious(): Observable<Pair<T?, T>> {
     return scan(listOf<T>(), { previous, current ->
         (previous + current).takeLast(2)
     }).skip(1).map { Pair(if (it.size > 1) it.first() else null, it.last()) }
}
```

**Comment by arkivanov** [comment]
Hi @dcvz, thanks for raising the issue, it helps us a lot. The implementation of the `scan` operator appears to be correct. E.g. according to RxJava [docs](https://github.com/ReactiveX/RxJava/blob/fd496db9a64320fcb9f9b4d110018bcd41e46c82/src/main/java/io/reactivex/rxjava3/core/Observable.java#L12234) it works same way.

The following test passes for RxJava:
```kotlin
    @Test
    fun testScan() {
        val observer = Observable.just(2).scan(1) { a, b -> a + b }.test()
        assertEquals(listOf(1, 3), observer.values())
    }
```

You can use the following implementation of `withPrevious` operator:
```kotlin
fun <T> Observable<T>.withPrevious(): Observable<Pair<T?, T>> =
    observable { emitter ->
        val previousRef = AtomicReference<T?>(null)

        subscribe(
            object : ObservableObserver<T>, CompletableCallbacks by emitter {
                override fun onSubscribe(disposable: Disposable) {
                    emitter.setDisposable(disposable)
                }

                override fun onNext(value: T) {
                    emitter.onNext(previousRef.getAndSet(value) to value)
                }
            }
        )
    }
```

**Comment by dcvz** [comment]
Thanks for the clarification @arkivanov 🙏 it’s also good to know the implementation is based on `RxJava`. Every library has its own quirks and naming and so far I’ve just been digging through the source code to figure things out.

I see now that the [ReactiveX](http://reactivex.io/documentation/operators/scan.html) website notes that the `RxJava` implementation emits the seed - as opposed to what other libraries do.

**Comment by arkivanov** [comment]
Yeah, you can always drop the first value if you don't need it.
