### ISSUE TITLE
BufferValuesWhileIdle

### ISSUE THREAD

**Issue by vchernyshov** [badoo/Reaktive#439]
Hello. 

I'm trying to implement buffer behaviour.
The main idea is to buffer values while other observable in idle state. Original varian based on RxJava I saw here: https://github.com/dmdevgo/RxPM/blob/develop/rxpm/src/main/kotlin/me/dmdev/rxpm/util/BufferWhileIdleOperator.kt
This is my implementation based on Reaktive:
https://gist.github.com/vchernyshov/5fcca5bf35a84a7eed3a7a5b88d288ab

It works but sometimes subscriber receives event on different scheduler.

Could your give some advice to solve this issue or maybe I made some conceptual mistakes when port RxJava solution?

Thanks.

**Comment by arkivanov** [comment]
Hello @vchernyshov ,

What you mean by "different scheduler"? I have checked your both RxJava and Reaktive implementations. I see that in both cases emissions to downstream can be performed on whatever scheduler upstream or `idleObserver` emit values. And this is normal. If you need to ensure any particular scheduler then you should use `observeOn` operator.

**Comment by vchernyshov** [comment]
@arkivanov thank's for you answer. I made inadvertently mistake when applied my operator to chain and this was the reason. Everything works as design.)

If you are interested, I use Reaktive to port RxPm library. Next step is to create MPP implementation.

https://github.com/vchernyshov/reaktive-pm

**Comment by arkivanov** [comment]
That's nice! Let us know if you have any questions. Also welcome to our Slack channel: https://kotlinlang.slack.com/archives/CU05HB31A
