### ISSUE TITLE
Support the new IR Backend for JS

### ISSUE THREAD

**Issue by agrosner** [badoo/Reaktive#440]
As per today's announcement, starting in 1.4-M1, KotlinJS [introduced](https://blog.jetbrains.com/kotlin/2020/03/kotlin-1-4-m1-released/) the new IR backend which can also generate Typescript definitions.
Please support the new backend, which will enable much better consumption of this library.

**Comment by arkivanov** [comment]
Thanks! We will check.

**Comment by arkivanov** [comment]
@agrosner I believe we should wait for the stable 1.4 release here.

**Comment by arkivanov** [comment]
Currently blocked by the following compiler bug: https://youtrack.jetbrains.com/issue/KT-41032

I will try to find a workaround.

**Comment by arkivanov** [comment]
There are multiple cases cousing the compilation error. Could not find a workaround. At the moment we have to wait.

**Comment by agrosner** [comment]
thanks for the updates, hopefully JB can fix these issues.

**Comment by arkivanov** [comment]
@agrosner Looks like it is now possible to enable the IR backend for JS. If have two questions: 
- How do you think, would it be enough to just enable the `both` mode?
- Will/can the `both` mode brake backward/binary/etc compatibility? I suppose no, but still.

**Comment by arkivanov** [comment]
Another blocker: https://youtrack.jetbrains.com/issue/KT-42073. Could not found a workaround for now.

**Comment by arkivanov** [comment]
Found a workaround, the build passed. Will try to release a final update to Jcenter.

**Comment by arkivanov** [comment]
Closed via #586
