### ISSUE TITLE
Change collections visibility

### ISSUE THREAD

**Issue by vchernyshov** [badoo/Reaktive#445]
Change visibility of collection from package `com.badoo.reaktive.utils.queue` to public it will allow  make thread safe custom operators for iOS target.

**Comment by arkivanov** [comment]
Thanks for raising the issue. Here are some explanations. We made things internal for a reason: we need flexibility without any binary compatibility obligations. Queue APIs in particular are changing from time to time, they even were refactored once. If we make them public then we will not be able to change.

Don't hesitate to copy-paste any code you need. Just use different package name so there will be no clashes.

**Comment by vchernyshov** [comment]
Ok, I got it) I will continue copy-paste approach))
