### ISSUE TITLE
Cannot access multi-platform classes on Android - missing or conflicting dependencies

### ISSUE THREAD

**Issue by Jafar-Al-Rashid** [badoo/Reaktive#451]
I have included the common package and it works ok on ios but just cannot access any of the reactive classes on android (the same shared code works on ios)
the error I am getting is:

Cannot access class 'com.badoo.reaktive.completable.CompletableWrapper'. Check your module classpath for missing or conflicting dependencies

tried this with 
kotlin 1.3.70, gradle 5.6.4 
and 1.3.72, gradle 6.0

any ideas what's going on here?

**Comment by arkivanov** [comment]
Hello,

I assume you want to use Reaktive in an Android app module. You need add the Reaktive dependency there as well: 

```groovy
dependencies {
    implementation "com.badoo.reaktive: reaktive:<version>"
}
```

Also make sure you have [Gradle metadata](https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#experimental-metadata-publishing-mode) enabled in your project.

**Comment by Jafar-Al-Rashid** [comment]
Yes, that's my problem, I have tried 
implementation ("com.badoo.reaktive:reaktive-jvm:1.1.12") and 
implementation ("com.badoo.reaktive:reaktive-android:1.1.12")

but did not try implementation "com.badoo.reaktive:reaktive:<version>"
it is working now, thanks

BTW - I need to create completable and observables on the iOS project, do I need to add any additional pods? If not, can you give me an example of how to create a completable on the ios project?

Thanks for your quick response

**Comment by arkivanov** [comment]
Unfortunately Generic types are [not exported to Swift for Kotlin interfaces](https://kotlinlang.org/docs/reference/native/objc_interop.html#generics). So you can't safely work with Reaktive from Swift. For this reason we have [wrappers](https://github.com/badoo/Reaktive#sharing-reaktive-streams-with-ios-swift), they are classes and can be normally exported.

I would suggest something like this:

Write a factory in Kotlin:
```kotlin
class MyObservableFactory {
    fun create(): ObservableWrapper<String> =
        observableFromFunction { "" } // Create your Observable somehow
            .wrap() // Wrap the Observable
}
```

Then get it in Swift:
```swift
let observable = MyObservableFactory().create()
```
