### ISSUE TITLE
Provide a non-null type constraint for better interop with swift

### ISSUE THREAD

**Issue by saket** [badoo/Reaktive#452]
Due to constraints related to how obj-c and swift handle nullable types, generic type parameters from kotlin get converted into nullable types unless they have a non-null constraint:

![image](https://user-images.githubusercontent.com/2387680/80562725-8ebc9c00-89b6-11ea-9e6e-9a56c1b1c05d.png)

Reaktive suffers from the same problem: its value callbacks receive a nullable types:

![image](https://user-images.githubusercontent.com/2387680/80562797-caeffc80-89b6-11ea-8523-057a1c2a7737.png)

Will it be possible to make this change in `ValueCallback`?

```kotlin
interface ValueCallback<in T : Any> {
```

**Comment by arkivanov** [comment]
The Generic type `T` of the `ValueCallback` is nullable by design. It is safe in Kotlin and Reaktive is a Kotlin library at the first place. But I understand your point. We could consider making `ObservableWrapper`'s Generic type `T : Any`. I'm not 100% sure but it should help. This will not brake binary compatibility but will break compilation in some cases, though it might be a good compromise. What do you think? Also guys @mk-jones @CherryPerry what do you think?

**Comment by arkivanov** [comment]
@saket Could you please try creating your own `MyObservableWrapper<T: Any>` and check whether it works good in Swift or not?

**Comment by mk-jones** [comment]
@arkivanov Perhaps something like a NonNullObservableWrapper<T: Any>? So the user can choose how we communicate the type to swift.

**Comment by CherryPerry** [comment]
Agree.

**Comment by arkivanov** [comment]
Will do this Friday 01/05

**Comment by saket** [comment]
> Could you please try creating your own MyObservableWrapper<T: Any> and check whether it works good in Swift or not?

Yep. I subclassed `ObservableWrapper` with `<T : Any>` and it correctly gets generated as a non-null type on obj-c. 

> Perhaps something like a NonNullObservableWrapper<T: Any>? So the user can choose how we communicate the type to swift.

Sounds good to me.

While we're at it, what do you think of adding overloaded `subscribe()` functions to wrapper classes? Default values for parameters don't get copied over to obj-c so users will be forced to always pass in values for `isThreadLocal`, `onSubscribe`, `onError` and `onComplete`. It'd be great if Kotlin MP supported this out of the box. I created an issue to track this: https://youtrack.jetbrains.com/issue/KT-38685

**Comment by arkivanov** [comment]
> what do you think of adding overloaded subscribe() functions to wrapper classes

Good point, will think about it, thanks!

**Comment by arkivanov** [comment]
Working on this currently. I still think that one non-null `ObservableWrapper<out T : Any>` will be better than two nullable and non-null. My points:

1. Nullable cases are rare, we mostly use non-null types (we also have `Maybe` that helps a lot)
2. If a user needs additional operators e.g. `map` they can extend just one class `ObservableWrapper` and add whatever needed. If there are two classes then the complexity may grow up to 4 times.
3. If there is a strong need to expose non-null types to Swift then something like a simple `Optional` may be used instead

Overall I believe it is better to have solid and non-confusing API for most of the cases. 

@mk-jones @CherryPerry @saket Waiting for your opinions!

**Comment by mk-jones** [comment]
Sounds fair to me

**Comment by saket** [comment]
Sounds fair to me as well, especially considering that reaktive's footprint may not be much on native platforms. People will probably convert them to `Combine` or `RxSwift` or something at the bridging layer.

**Comment by arkivanov** [comment]
@saket Released!

**Comment by saket** [comment]
🎉
