### ISSUE TITLE
IOS: How to subscribe to observable on main async thread (DispatchQueue.main.async)?

### ISSUE THREAD

**Issue by mikezliu** [badoo/Reaktive#455]
I'm performing some background work on ioScheduler and then need to read some values from a datastore. The data store is implemented in KN and can't be frozen, so I believe I need to access it from the main thread.

In Swift code I usually use DispatchQueue.main.async to access it without blocking the UI thread, but I'm trying to move this code into KN using Reaktive observables. Is there a way to access the data store on the main async thread from a reaktive stream? There's ioScheduler (background) and mainScheduler, though I am not sure if mainScheduler can be modified to run in the main async or whether it blocks the UI thread.

**Comment by mikezliu** [comment]
Looking at https://github.com/badoo/Reaktive/blob/master/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/looperthread/FixedLooperThreadStrategy.kt it does seem to create a new thread. So is it correct to say using mainScheduler on iOS will run on the main async thread?

**Comment by arkivanov** [comment]
Reaktive's `mainScheduler` uses `platform.darwin.dispatch_after` with `import platform.darwin.dispatch_get_main_queue`. You can check the implementation [here](https://github.com/badoo/Reaktive/blob/da92519b19fc83ecd17d5e134d4d7202eeed0a5c/reaktive/src/darwinCommonMain/kotlin/com/badoo/reaktive/scheduler/MainScheduler.kt#L40). So it's equivalent to `DispatchQueue.main.async` which just schedules the execution immediately but allows current thread to continue.

I believe your case is covered in the README [here](https://github.com/badoo/Reaktive#thread-local-tricks-to-avoid-freezing). You need to use `observeOn(mainScheduler) and either `threadLocal()` operator or `susbcribe(isThreadLocal = true, ...)`.

**Comment by mikezliu** [comment]
Ok thanks!
