### ISSUE TITLE
Bump GitHub Actions checkout version from v1 to v2

### ISSUE THREAD

**Issue by mayokunthefirst** [badoo/Reaktive#457]
Hi, I just went through the workflow for this project and noticed it still uses `actions/checkout@v1`. Although this doesn't seem to break this project, I have had issues like [this](https://github.com/actions/checkout/issues/222) with v1 in my most recent project. Maybe you could consider bumping to v2 ? Have a look at the releases: [actions/checkout/releases](https://github.com/actions/checkout/releases). I'll also love to help get this done.

**Comment by arkivanov** [comment]
Yeah we also had this error a couple of times, thanks!

**Comment by arkivanov** [comment]
>  I'll also love to help get this done

Sold!

**Comment by arkivanov** [comment]
Thanks @mayokunthefirst !

**Comment by mayokunthefirst** [comment]
> Thanks @mayokunthefirst !

Always happy to help 👍
