### ISSUE TITLE
Making DisposableScope stable, feedback wanted!

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#459]
The `DisposableScope` seems very useful, now it's time to remove the `@ExperimentalReaktiveApi` annotation. Please tell us if you see something could be improved!

**Comment by arkivanov** [comment]
My input: to remove [`fun <T : CompleteCallback> T.scope(): T`](https://github.com/badoo/Reaktive/blob/9a232df87ecf275e7bdf04b2cc53e0b6a1f72f59/reaktive/src/commonMain/kotlin/com/badoo/reaktive/disposable/scope/DisposableScope.kt#L27) method. This method should be rarely used and can be replaced with `Disposable(whatever::onComplete).scope()`. On the other hand it produces ambiguity if an object conforms to both `Disposable` and `CompleteCallback` interfaces.

**Comment by mk-jones** [comment]
I'm happy to see it made stable. 
I generally have only used the scope and subscribeScoped methods.
Removing fun <T : CompleteCallback> T.scope(): T wouldn't bother me.
