### ISSUE TITLE
Print error stacktrace when TestObserver.assertNotError() fails

### ISSUE THREAD

**Issue by saket** [badoo/Reaktive#462]
Printing `"Source failed"` is not very useful when `test().assertNotError()` is used in a test. What do you think of printing the error stacktrace as well?

**Comment by arkivanov** [comment]
This makes sense, will add. Thanks!

**Comment by arkivanov** [comment]
PR welcome btw

**Comment by saket** [comment]
I can try sending it but can't commit a date 😄
