### ISSUE TITLE
:reaktive:linuxX64Test task fails

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#479]
I have the following error when I run `:reaktive:linuxX64Test` locally from AS.

![image](https://user-images.githubusercontent.com/26204457/83976188-6b0f3e80-a8f0-11ea-8056-aebe90df6f41.png)

**Comment by arkivanov** [comment]
Hmm, it failed once but now looks like fine. Let's keep an eye.

**Comment by CherryPerry** [comment]
https://youtrack.jetbrains.com/issue/KT-37362
https://youtrack.jetbrains.com/issue/KT-37565
