### ISSUE TITLE
Collection<Observable<T>>.combineLatest will never complete if collection is empty

### ISSUE THREAD

**Issue by amihusb** [badoo/Reaktive#500]
Hi, i faced a problem that `Observable.combineLatest` will not complete if collection of `Observable's` is empty.
This simple test case failed:
```kotlin
@Test
fun completed_when_collection_is_empty() {
    val observer = emptyList<Observable<Any>>()
        .combineLatest { it }
        .test()
    observer.assertNoValues()
    observer.assertComplete()
}
```

Also some of operators such as: `amb`, `merge`, `zip`, `withLatestFrom` also works incorrect. Whereas `concat` operators handle this case, so does [RxJava](https://github.com/ReactiveX/RxJava/blob/d209606e0eaaf87bb5493fd71a8413822f9992f2/src/main/java/io/reactivex/rxjava3/internal/operators/observable/ObservableCombineLatest.java#L70)
Furthermore there is different reciever type for collection: [Iterable](https://github.com/badoo/Reaktive/blob/6ae4e8caf147e784f21f16dcc49a6b8fe8ed6d92/reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Concat.kt#L8) and [Collection](https://github.com/badoo/Reaktive/blob/6ae4e8caf147e784f21f16dcc49a6b8fe8ed6d92/reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/CombineLatest.kt#L13)

So i have some questions:
- Which type should be receiver: Iterable or Collection?
- Should i optimize operators with `size == 1` checks?
- Should i make single PR or per stream?

For example, what i want to do:
```kotlin
fun <T, R> Collection<Observable<T>>.combineLatest(mapper: (List<T>) -> R): Observable<R> =
    when (size) {
        0 -> observableOfEmpty()
        1 -> first().map { value -> mapper.invoke(List(1) { value }) }
        else -> internalCombineLatest(mapper)
    }

private fun <T, R> Collection<Observable<T>>.internalCombineLatest(mapper: (List<T>) -> R): Observable<R>
```

**Comment by arkivanov** [comment]
Hey @amihusb, thanks for raising the issue. This is a bug indeed.

Answering your questions:

> Which type should be receiver: Iterable or Collection?

The reason why it's `Collection` is because we need `size`. RxJava copies the content into an array. With Reaktive we can write something like this:

```kotlin
myIterable.toList().combineLatest(...)
```

Let's keep `Collection` type for now.

> Should i optimize operators with size == 1 checks?

No need to optimize currently.

> Should i make single PR or per stream?

I would prefer a single PR.

PS: I'm suggesting to fix this in the following way:

```
Index: reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/CombineLatest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/CombineLatest.kt	(revision db9c26d5258b071d6d76d472c3fcd5080b2c53eb)
+++ reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/CombineLatest.kt	(date 1594048765000)
@@ -12,6 +12,11 @@
 
 fun <T, R> Collection<Observable<T>>.combineLatest(mapper: (List<T>) -> R): Observable<R> =
     observable { emitter ->
+        if (isEmpty()) {
+            emitter.onComplete()
+            return@observable
+        }
+
         val disposables = CompositeDisposable()
         emitter.setDisposable(disposables)
         val values = SharedList<Any?>(size) { Uninitialized }

```

Also please add unit tests for such cases.

Thanks for your contribution!
