### ISSUE TITLE
Run tests for linuxArm32Hfp target

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#504]
The `linuxArm32Hfp` target can be built on any host, however running tests requires an ARM host. This is the reason why tests for this target are not running on CI currently. Looks like ARM is supported by GitHub Actions.

We need to investigate possible solutions and try to enable `linuxArm32Hfp` tests on CI.

Keep in mind, currently there is no corresponding Gradle task like `linuxArm32HfpTest`.

**Comment by arkivanov** [comment]
If this will be successful then we could add `linuxArm64` target as well, to support devices like Raspberry Pi.

**Comment by arkivanov** [comment]
Thanks @temq09 for wanting to take this task! You can collaborate with @CherryPerry to find a way of adding `linuxArm32HfpTest` Gradle task.

**Comment by CherryPerry** [comment]
I suggest to start with creating ARM CI configuration without `-Ptarget` specification and execute `linuxArm32HfpTest`.
I have a feeling, that this task will be registered on ARM machine in the same way, as `macosX64Test` on MacOS.

**Comment by arkivanov** [comment]
@CherryPerry The thing is that on my Linux machine I have all Apple test tasks, but can't run them obviously. But I don't have the `linuxArm32HfpTest` task.

**Comment by CherryPerry** [comment]
With some hacks I successfully set up task for launching tests, but I can't set up TravisCI properly for running them. (GitHub Actions does not support ARM).

https://github.com/CherryPerry/Reaktive/tree/test-linuxArm32Hfp

**Comment by arkivanov** [comment]
@CherryPerry I'm not really familiar with GitHub Actions, but this is what I found:
https://github.com/uraimo/run-on-arch-action
https://github.com/marketplace/actions/docker-buildx
Also maybe we could setup a self hosted runner?
Or get help from somewhere about TravisCI...

**Comment by arkivanov** [comment]
Just throwing ideas

**Comment by CherryPerry** [comment]
I somehow managed to create valid Travis configuration, but looks like my Gradle setup does not work properly. Or somehow patch it.

The _easiest_ solution is to fork Kotlin repository and change hardcoded configuration [here](https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/plugin/mpp/KotlinMultiplatformPlugin.kt#L162) and [here](https://github.com/JetBrains/kotlin/blob/5e1e9876fda22e35088077953012b17d76c870aa/native/utils/src/org/jetbrains/kotlin/konan/target/HostManager.kt#L147).

**Comment by arkivanov** [comment]
@CherryPerry Thanks! Good investigation!

**Comment by CherryPerry** [comment]
> e: java.lang.UnsatisfiedLinkError: /home/travis/.konan/kotlin-native-linux-1.3.72/konan/nativelib/tmp7739326964854683208.tmp/libllvmstubs.so: /home/travis/.konan/kotlin-native-linux-1.3.72/konan/nativelib/tmp7739326964854683208.tmp/libllvmstubs.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a AARCH64-bit platform)

It is impossible to compile Kotlin native code on ARM machine. The only way to launch test it to pass binary directly on ARM machine and launch it. https://github.com/uraimo/run-on-arch-action can help.
