### ISSUE TITLE
Enable HMPP

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#523]
Would be nice to enable, but currently blocked by [KT-41160](https://youtrack.jetbrains.com/issue/KT-41160).

**Comment by omainegra** [comment]
Could it be possible to use the workaround suggested in the ticket in the meantime?

**Comment by arkivanov** [comment]
I will try. But I remember there were more compilation errors. Also according to multiple reports this feature is really buggy and looks unfinished. Personally I could not enable it in any of my projects.

**Comment by arkivanov** [comment]
Just in case, sharing code between targets is possible for a long time already. There is just no IDE support for this, but there are workarounds though.

**Comment by omainegra** [comment]
It's bad to hear that, I'm migrating one library project and it's actually working, and the build script is way simpler now, just for publishing I'm disabling it

**Comment by arkivanov** [comment]
Yeah, I understand. I will try one more time, but most likely it won't work at the moment.

**Comment by arkivanov** [comment]
Fol a library development it should not be a blocker, since code sharing is possible in any intermediate source set. E.g. jvmCommonMain can even depend on both jvmJsCommonMain and jvmNativeCommonMain at the same time.

**Comment by arkivanov** [comment]
IDE can be temporary made happy with a workaround

**Comment by arkivanov** [comment]
Just tried one more time. Another blocker is that with HMPP enabled we can't access `platform.*` in the `nativeCommonMain` source sets (in our case it is shared between all Linux and Darwin targets). E.g. `platform.posix.fprintf` does not compile. We have plenty of code there. In order to compile this with HMPP we need to duplicate this for Linux and Darwin. And perhaps Darwin should be also split (not sure yet). This significantly increases amount of code (duplicated one) and makes it harder to maintain. Failed the issue: [KT-42574](https://youtrack.jetbrains.com/issue/KT-42574).

At the moment it is better to wait for improvements in HMPP.

**Comment by arkivanov** [comment]
But let's collect use cases! It should be possible to use a library published without HMPP in a project with HMPP enabled, and access its common code from any HMPP shared source set. Only library code from a shared source set might not be accessible.

**Comment by omainegra** [comment]
Thanks for the efforts, in my case it's completely fine to use HMPP and still use Reaktive, the only thing I have to do since my project is also a library is disabled it during publish (`./gradlew -Pkotlin.mpp.enableGranularSourceSetsMetadata=false publish`)

**Comment by arkivanov** [comment]
The following issues are still relevant:
- [KT-41509](https://youtrack.jetbrains.com/issue/KT-41509) // A workaround is available, but there is quite a lot of duplicated code
- [KT-48811](https://youtrack.jetbrains.com/issue/KT-48811) // A workaround is available
- [KT-43309](https://youtrack.jetbrains.com/issue/KT-43309) // A workaround is available, but there is quite a lot of duplicated code

**Comment by arkivanov** [comment]
Closed via #662, version [1.2.2](https://github.com/badoo/Reaktive/releases/tag/1.2.2) is released.
