### ISSUE TITLE
Support new IR compiler for Kotlin/JS

### ISSUE THREAD

**Issue by omainegra** [badoo/Reaktive#533]
https://kotlinlang.org/docs/reference/migrating-multiplatform-project-to-14.html#changes-related-to-the-kotlinjs-ir-compiler

This is needed to generate TypeScript definitions from your Kotlin code. More info here: https://kotlinlang.org/docs/reference/js-ir-compiler.html#preview-generation-of-typescript-declaration-files-dts

**Comment by arkivanov** [comment]
Looks like this duplicates #440 
This task is blocked by two compilation issues.

**Comment by omainegra** [comment]
Yes, it's the same. Thank you
