### ISSUE TITLE
Add cache() operator

### ISSUE THREAD

**Issue by MarcelHeckel** [badoo/Reaktive#539]
Hi,

in RxJava there are also [SingleSubject](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/subjects/SingleSubject.html) and [CompletableSubject](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/subjects/CompletableSubject.html).

They are useful to do a computation only once and publish the result to all subscribers,  

If I want to do the something similar with Reaktive, I have to use a `ReplaySubject `with `onNext()` followed by `onComplete()`. 

        val s = ReplaySubject<Int>();

        s.subscribe { println("#1 -> $it") }

        println("doing....")
        s.onNext(1)
        s.onComplete();

        s.subscribe { println("#2 -> $it") }
        s.subscribe { println("#3 -> $it") }

Printing

    doing....
    #1 -> 1
    #2 -> 1
    #3 -> 1

If I use the `single()` function of Reaktive the computation is done each time:

       @Test
        val s= single<Int> {
            println("doing....")
            it.onSuccess(1);
        }

        s.subscribe { println("#1 -> $it") }
        s.subscribe { println("#2 -> $it") }
        s.subscribe { println("#3 -> $it") }
 
Printing:

    doing....
    #1 -> 1
    doing....
    #2 -> 1
    doing....
    #3 -> 1

Or I need a hack like this (which also does not consider race conditions):

      val s = single(object : (SingleEmitter<Int>) -> Unit {
            var result: Int? = null
            override fun invoke(emitter: SingleEmitter<Int>) {
                if (result == null) {
                    println("doing....")
                    result = 1
                }
                emitter.onSuccess(result!!)
            }
        }
        )

**Comment by arkivanov** [comment]
Hello @MarcelHeckel, thanks for raising the issue!

`CompletableSubject` and `SingleSubject` can be trivially implemented as follows:
```kotlin
class CompletableSubject private constructor(
    private val subject: Subject<Nothing>
) : Completable by subject.asCompletable(), CompletableCallbacks by subject {
    constructor() : this(PublishSubject())
}

class SingleSubject<T> private constructor(
    private val subject: Subject<T>
) : Single<T> by subject.firstOrError(), SingleCallbacks<T>, ErrorCallback by subject {

    constructor() : this(ReplaySubject())

    private val isSuccess = AtomicBoolean()

    override fun onSuccess(value: T) {
        if (isSuccess.compareAndSet(false, true)) {
            subject.onNext(value)
        }
    }
}
```

Since they are rarely used, at the moment I don't think we should add them into the library.

However, according the provided use cases you need lazy calculation, which should be done via `cache()` operator. We can add this one.

Meanwhile you can quickly implement `cache` operator on your own as follows:
```kotlin
fun <T> Single<T>.cache(): Single<T> =
    asObservable()
        .replay()
        .autoConnect()
        .firstOrError()
```

**Comment by MarcelHeckel** [comment]
@arkivanov OK. Thank you for the hints!

**Comment by arkivanov** [comment]
Renamed the issue to "Add cache() operator"

**Comment by arkivanov** [comment]
Considering that the `cache` operator would just be a shortcut to `replay().autoConnect()`, and that the `cache` operator is rarely used, I think it is better not to add it to the library for now. Until there is significant demand.
