### ISSUE TITLE
BehaviorSubject subject.value is not set immediately after onNext

### ISSUE THREAD

**Issue by kabirsaheb** [badoo/Reaktive#541]
Hello,
I have been using Reaktive since a week and saw that BehaviorSubject sets value (_value) in onBeforeNext which is called some point later when serializer calls onSerializedValue
Is this expected behavior?

The problem I am facing is, I am using BehaviorSubject to store some state and immediately after onNext if I read the value it does not reflect the latest value and wrong value is being set again. (PS: I am using this in Store in Mvi pattern but my State is global like Redux app) I am making sure that only one thread is allowed to read and write to store's state (Stored in behavior subject) still I end up getting wrong state due to this behavior. Currenly I am using below workaround. 

```
class Store(initialState: GlobalState): StoreInterface, DisposableScope by DisposableScope() {
    private val subject = BehaviorSubject(initialState)
    private var currentState: GlobalState = initialState

    override fun getState(): GlobalState {
        // FIXME: 18/09/20 
        //  subject.value does not give latest value if called immediately after onNext so maintaining separate var
        // return subject.value
        return currentState
    }

    override fun setState(newState: GlobalState) {
        currentState = newState
        subject.onNext(newState)
    }

    override fun subscribe(observer: ObservableObserver<GlobalState>) {
        subject.subscribe(observer)
    }
}
```

If BehaviorSubject is indeed correct as per Rx specifications, can you suggest any better workaround to the issue? If DefaultSubject can be made public then also we can make our own custom Subject where value can be set in onNext itself rather than onBeforeNext

**Comment by arkivanov** [comment]
Hello. BehaviourSubject sets its value before calling subscribers. The only case when it won't set the value immediately is when you call onNext recursively, while previous value is being emitted. The latter looks like a bug. I will check this and fix is needed. Thanks.

**Comment by kabirsaheb** [comment]
Thanks yes I am calling onNext recursively.

**Comment by arkivanov** [comment]
I investigated this case and here are some results:
- RxJava `Subjects` do not support recursive invocations by default (they are not reentrant)
- Any RxJava `Subject` can be serialized via `subject.toSerialized()` method
- Serialized RxJava `Subjects` support recursive invocations
- Reaktive `Subjects` are serialized by default and so support recursive invocations as well
- Both serialized RxJava and Reaktive `BehaviorSubjects` do not set value immediately when calling `onNext` recursively, the second event is scheduled and is processed when the first `onNext` call returns

Here is the RxJava sample code:
```kotlin
        val subject = BehaviorSubject.create<Int>()
        val serializedSubject = subject.toSerialized()
        subject.subscribe {
            if (it == 0) {
                serializedSubject.onNext(1)
                Log.v("MyTest", "value: ${subject.value}")

            }
        }
        serializedSubject.onNext(0)
```

The output is: `value: 0`. The Reaktive `BehaviorSubject` implementation is correct in this case.

---
Now about your case. We are also using both Reaktive and RxJava for MVI and never experienced this problem. It is not clear where and why do you read the state. But I would guess, you may want to read the updated state from inside the store. In this case you need to use `PublishSubject` for `Intents`. You should make sure your `Store` does not process `Intents` recursively:

```kotlin
class Store<Intent> : DisposableScope by DisposableScope(), /*More interfaces here*/ {
    private val intents = PublishSubject<Intent>()

    init {
        intents.subscribe(onNext = ::onIntent).scope()
    }

    private fun onIntent(intent: Intent) {
        // This method won't be invoked recursively
        // It is save to update the state from here
    }

    fun accept(intent: Intent) {
        intents.onNext(intent)
    }
}
```

**Comment by kabirsaheb** [comment]
Hey Thanks for investigation!

My case FYI. I am currently using below logic. There are 2 types of actions. Middleware and Reducer. A middleware action can spawn multiple actions (Middleware + Reducers) A middleware can call below onNext method outside subscribeScoped also. Which allows me to run two independant observers parallelly. If there is any single middleware which can cause update to state multiple times using reducer in single onNext at that time this line `store.setState(type.run(store.getState()))` gives wrong getState

```
override fun onNext(value: Action) {
        when (val type = value.type) {
            is ActionType.Middleware -> {
                type.run(this)?.observeOn(mainScheduler)?.subscribeScoped(onNext = ::onNext)
            }
            is ActionType.Reducer -> {
                store.setState(type.run(store.getState()))
            }
        }
    }
```

**Comment by arkivanov** [comment]
I still don't have full picture, so can't point to a particular place. In general, you should not update `Store` state while it is being emitted (from the state subscription). Normally `Store` should have a `Reducer` and `Intents`. `Store` should consume `Intents` and reduce its state internally using the `Reducer`. This [article](https://medium.com/bumble-tech/mvi-in-kotlin-multiplatform-part-1-1-of-3-205c6feb4ac7) may be helpful.

**Comment by arkivanov** [comment]
Anyway your workaround seems legit and working.

**Comment by kabirsaheb** [comment]
> In general, you should not update `Store` state while it is being emitted (from the state subscription).

Sure. Thank you for your time

**Comment by arkivanov** [comment]
Closing this one. Feel free to reopen if there are any questions.
