### ISSUE TITLE
Publish to Maven Central or JCenter

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#550]
Bintray is good but its repository should be explicitly added to build.gradle if Reaktive is used transitively by some another library.

**Comment by arkivanov** [comment]
I submitted a request to sync our Bintray repository to JCenter and received the following response:

> We see that the following artifact IDs do not have the sources.jar file in it.
> 
> rxjava2-interop
> rxjava3-interop
> 
> In addition to the .pom file and the .aar file, your version should include, a sources jar, and optionally a javadoc jar. Kindly update the package with the required files so that we can approve your request.

@CherryPerry how do you think is it possible to fix this issue?

**Comment by CherryPerry** [comment]
I hope it is easy. Will check tomorrow.
https://github.com/bintray/gradle-bintray-plugin#step-7-define-artifacts-to-be-uploaded-to-bintray
```gradle
publishing {
    publications {
        MyPublication(MavenPublication) {
            from components.java
            artifact sourcesJar
            artifact javadocJar
        }
    }
}
```
