### ISSUE TITLE
Add shortcut of subscribe {}

### ISSUE THREAD

**Issue by thunderstorm010** [badoo/Reaktive#564]
Add a shortcut of subscribe {} to subscribe() so it will be less confusing.

This is an example:
```kt
fun Single<*>.subscribe() {
     this.subscribe {}
}
```

**Comment by arkivanov** [comment]
Hello! The existing extension with callbacks has all arguments with default values. So you can call it without arguments. Will it work for you?

**Comment by arkivanov** [comment]
```kotlin
import com.badoo.reaktive.single.Single
import com.badoo.reaktive.single.subscribe

fun foo(single: Single<String>) {
    single.subscribe()
}
```

**Comment by arkivanov** [comment]
Closing this issue for now. Feel free to reopen if there are any questions.
