### ISSUE TITLE
Crashes inside Reaktive streams are not recorded into Firebase Crashlytics on iOS

### ISSUE THREAD

**Issue by 7effrey** [badoo/Reaktive#565]
Hello,

I tried to `throw Exception("Test")` inside Reaktive stream for example in `onNext()` without adding `onError()` handling.
On Android, it has no issue as it's recorded on Crashlytics
<img width="739" alt="Screenshot 2020-11-19 at 9 23 44 AM" src="https://user-images.githubusercontent.com/1018977/99608505-fd437300-2a48-11eb-8371-e2be17192caa.png">

However on iOS, that crash is not recorded on Crashlytics (I have ensure that dSYMs have been uploaded and it has no issue if I throw Exception outside of Reaktive stream).

I think it's because the uncaught error handler in here [https://github.com/badoo/Reaktive/blob/master/reaktive/src/nativeCommonMain/kotlin/com/badoo/reaktive/utils/CreateDefaultUncaughtErrorHandler.kt]

It will exitProcess which is terminating the app without propagating the error to the iOS. Is there any workaround to propagate this error?

Thanks.

**Comment by arkivanov** [comment]
Hello @7effrey. You are right, this is how the default uncaught error handler is designed. The reason behind such a behaviour is that exceptions thrown in a background thread (e.g. a Kotlin/Native Worker) do not interrupt/crash the main thread, and so the app continues working as normal. That's why Reaktive does not re-throw exceptions in the default uncaught error handler, but prints the error and does `exitProcess`.

I will check if there is any way to call the default exception handler in iOS, same as it is done in JVM.

Meantime you can override the uncaught error handler as follows:
```kotlin
    reaktiveUncaughtErrorHandler = { e ->
        fprintf(stderr, "Uncaught exception: $e")
        e.printStackTrace()

        // TODO: Log the error to Crashlytics here

        exitProcess(EXIT_FAILURE)
    }
```

I will also mention this in the README. Thanks for raising!

**Comment by arkivanov** [comment]
I think doing `platform.posix.abort()` instead of `exitProcess(...)` should solve the problem? What are your opinions? @7effrey @wiruzx

**Comment by 7effrey** [comment]
Hi @arkivanov ,

Thanks for your suggestion. I have tested it with those 2 suggestions below:
`reaktiveUncaughtErrorHandler = { e ->
    println("Uncaught exception: $e")
    e.printStackTrace()
    loggerService?.log("Uncaught Exception", e)
    platform.posix.abort()
}`

1. platform.posix.abort(): it works well because the throwable can be caught by Firebase Crashlytics on iOS which is the similar behavior as on Android.
<img width="1095" alt="Screenshot 2020-11-21 at 3 53 17 PM" src="https://user-images.githubusercontent.com/1018977/99870947-bfde1180-2c11-11eb-8c93-e5b178903e09.png">

The only downside is the limited stacktrace that refers to our Kotlin Multiplatform code but at least it can show the trigger on our iOS code (i.e. MovieViewController.buttonClicked() + 114).


2. Record uncaught error to Firebase Crashlytics: When we record this manually, it will be recorded as Non-Fatal Exception and it's a bit difficult to parse List<String> (from Throwable.getStacktrace()) to be an ExceptionModel. So, the non-fatal exception log won't be informative enough.

Here is my implementation of `loggerService?.log("Uncaught Exception", e)`
`func log(key: String, throwable: KotlinThrowable) {
    let exceptionModel = ExceptionModel.init(name: key, reason: throwable.message ?? "")
    let iterator = throwable.getStackTrace().iterator()
    var clsStackTrace: [StackFrame] = []
    while (iterator.hasNext()) {
        guard let message = iterator.next_() as? String else { break }
        clsStackTrace.append(StackFrame.init(symbol: message, file: "", line: 0))
    }
    exceptionModel.stackTrace = clsStackTrace
    getInstance().record(exceptionModel: exceptionModel)
}`

And here is the record on Firebase Crashlytics dashboard:
<img width="1071" alt="Screenshot 2020-11-21 at 3 59 30 PM" src="https://user-images.githubusercontent.com/1018977/99871068-9ffb1d80-2c12-11eb-8214-1f4539ed1130.png">
<img width="1117" alt="Screenshot 2020-11-21 at 3 59 55 PM" src="https://user-images.githubusercontent.com/1018977/99871071-a7222b80-2c12-11eb-992e-50d6ef5b98b1.png">

So, I guess `platform.posix.abort()` is a better workable solution.

Thanks for your help.

**Comment by arkivanov** [comment]
Oops, looks like I forgot to send my response. I will add `abort()` today.
