### ISSUE TITLE
 I have complications when implementing the library in my kotlin multiplatform project

### ISSUE THREAD

**Issue by angelhr28** [badoo/Reaktive#569]
Failed to resolve: com.badoo.reaktive:utils-android:1.1.18-nmtc
Affected Modules: shared

**Comment by arkivanov** [comment]
This is because only `coroutines-interop` module is published in two variants: normal and `-nmtc`. Could you please apply `-nmtc` version suffix only to that module?

**Comment by angelhr28** [comment]
Could not find com.badoo.reaktive:reaktive:1.1.18.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/badoo/reaktive/reaktive/1.1.18/reaktive-1.1.18.pom
  - https://jcenter.bintray.com/com/badoo/reaktive/reaktive/1.1.18/reaktive-1.1.18.pom
  - https://jitpack.io/com/badoo/reaktive/reaktive/1.1.18/reaktive-1.1.18.pom
Required by:
    project :androidApp > project :shared

**Comment by angelhr28** [comment]
![image](https://user-images.githubusercontent.com/43622761/101203255-68d83380-3638-11eb-9113-6034b76fd918.png)

**Comment by arkivanov** [comment]
I see that it does not check our repository. Could you please add it to the list?

```
repositories {
    maven {
        url  "https://dl.bintray.com/badoo/maven"
    }
}
```

**Comment by angelhr28** [comment]
If I check the documentation, I already have it added in the maven; the synchronization with the gradle is correct, the problem comes when I want to run the project.

**Comment by arkivanov** [comment]
Could you please share your build configs? According to the provided screenshots, it does not check our repository.

**Comment by angelhr28** [comment]
![image](https://user-images.githubusercontent.com/43622761/101227500-14e44380-3666-11eb-8d46-421d7dd08876.png)
![image](https://user-images.githubusercontent.com/43622761/101227542-347b6c00-3666-11eb-858f-f400300ebdb2.png)

**Comment by arkivanov** [comment]
It's first time I see multiple URLs per repository definition. Could you please try splitting it? Like:
maven { url = ... }
maven { url = ... }

If it won't help, I would ask you to provide a reproducer project. Something is wrong with build configuration.
