### ISSUE TITLE
Introduce a way to intercept operator assembly calls

### ISSUE THREAD

**Issue by saket** [badoo/Reaktive#574]
Debugging errors with reaktive is a bit difficult right now if streams involve thread hopping because error stacktraces don't include traces from all threads on the JVM (and maybe native too?). Offering a way to intercept/hook into operator assembly calls may enable creation of something like [Traceur](https://github.com/T-Spoon/Traceur) for better stacktraces during development.

**Comment by arkivanov** [comment]
Thanks for raising. Indeed, we should add something similar.

Could you please elaborate, what you mean by "traces from all threads"? As far as I know, Traceur just appends original stack trace when an operator is created. Not like "all threads".

**Comment by saket** [comment]
I'm not an expert, but from what I understand, Traceur collects a stacktrace everytime an operator is assembled which may happen in different threads. When a crash occurs, Traceur appends all those stacktraces as "causes" to the final throwable. Without traceur, reaktive/rxjava will only contain a stacktrace for the thread where the crash occurred.

**Comment by arkivanov** [comment]
Thanks, we will think about it.
