### ISSUE TITLE
Timeout operator with a message

### ISSUE THREAD

**Issue by rubtsovnyu** [badoo/Reaktive#579]
So now `timeout` operator will throw a TimeoutException without any message to the subscriber if the timeout has expired. Is it possible to add a `message` argument to this operator?

Like:
```kotlin
observable<Message> {}
        .timeout(10, ioScheduler, "Timed out on waiting for incoming message.")
```

**Comment by arkivanov** [comment]
Hello! Thanks for the question. You can make your own `timeout` extension as follows:

```kotlin
fun <T> Observable<T>.timeout(timeoutMillis: Long, scheduler: Scheduler, message: String): Observable<T> =
    timeout(timeoutMillis = timeoutMillis, scheduler = scheduler)
        .onErrorResumeNext {
            observableOfError(if (it is TimeoutException) TimeoutWithMessageException(message) else it)
        }

class TimeoutWithMessageException(message: String) : Exception(message)
```

Currently it is not possible to supply a message for the `TimeoutException`, so you need to create your own `TimeoutWithMessageException`. But we can add the `message` argument to `TimeoutException`, if this would help.

**Comment by rubtsovnyu** [comment]
I don't think it really makes sense without bundled `timeout(message)` function. Thank you for the answer anyway.
