### ISSUE TITLE
Migrate away from Bintray and Jcenter

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#580]
They both are going away https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
We need to investigate our possibilities and migrate publications somewhere.

**Comment by arkivanov** [comment]
Cc/ @CherryPerry

**Comment by arkivanov** [comment]
![Screenshot_20210203-185643](https://user-images.githubusercontent.com/26204457/106795109-98fc7c80-6651-11eb-82f4-cbc696b1b40c.png)

**Comment by CherryPerry** [comment]
https://blog.autsoft.hu/publishing-an-android-library-to-mavencentral-in-2019/

**Comment by CherryPerry** [comment]
As an alternative: Mirror this repo to GitLab, build on GitLab CI (400 minutes per month for releases only should be enough) and deploy on GitLab Packages (have not found any restrictions).

**Comment by CherryPerry** [comment]
GitHub packages are useless for now. 500 MB storage limit and 1G traffic limit. Probably we can wait some time, they can respond with making packages free to use. Also API is terrible, you basically need to provide GitHub account API key to be able to download artefacts. If these 2 issues are fixed, probably it will become preferable solution (much easier than maven central setup).

**Comment by arkivanov** [comment]
Thanks @CherryPerry, I raised a question to try registering with Maven Central.

**Comment by arkivanov** [comment]
@CherryPerry  I think we can already start migration to `maven-publish` plugin? Would you like to take this task?

**Comment by CherryPerry** [comment]
Will do

**Comment by arkivanov** [comment]
A fresh guide from the same author: https://getstream.io/blog/publishing-libraries-to-mavencentral-2021/

**Comment by CherryPerry** [comment]
@arkivanov Do you know, will it be possible to use `check-publication`?

**Comment by arkivanov** [comment]
> @arkivanov Do you know, will it be possible to use `check-publication`?

I'm not 100% sure. There is staging repository that looks like can be used for this purpose

**Comment by arkivanov** [comment]
Found this GitHub action, maybe we'll need it: https://github.com/martinbonnin/create-nexus-staging-repo-sample

**Comment by arkivanov** [comment]
The `signing` plugin supports in-memory keys, as per [documentation](https://docs.gradle.org/current/userguide/signing_plugin.html#sec:in-memory-keys), which can be provided via environment variables in CI.
@CherryPerry FYI

**Comment by arkivanov** [comment]
When publishing from different hosts, Nexus Package Manager creates separate staging repositories for publications from each host. We can avoid it by creating a new repository beforehand and then use its id for uploading. Example: https://github.com/nexus-actions/nexus-actions-demo

**Comment by arkivanov** [comment]
Javadocs are required by Maven Central, we can upload just empty jars for now: found a [sample](https://github.com/h0tk3y/k-new-mpp-samples/blob/71ae083c84de8f484ad6ed1d7317c2524a2229f4/publish-to-maven-central/build.gradle.kts#L79).

**Comment by arkivanov** [comment]
@CherryPerry We can derive some publication workflow steps:
- [Create temporary repository] and get its id (https://github.com/arkivanov/Decompose/blob/818f1cda7a86b0bd162284ecd8b80e73663a9289/.github/workflows/publish.yml#L9)
- Sign and publish artifacts using the temporary repository id (https://oss.sonatype.org/service/local/staging/deployByRepositoryId/${System.getenv("SONATYPE_REPOSITORY_ID")})
- [Close the temporary repository](https://github.com/arkivanov/Decompose/blob/818f1cda7a86b0bd162284ecd8b80e73663a9289/.github/workflows/publish.yml#L76) - artifacts are moved to the public staging repository (https://oss.sonatype.org/service/local/staging/deploy/maven2)
- Verify publications
- If successful, **manually** release artifacts from the admin panel
