### ISSUE TITLE
Allow nullable types in wrapper classes

### ISSUE THREAD

**Issue by endanke** [badoo/Reaktive#594]
Hello!

I would like to expose an observable in Swift which has a nullable type and I just noticed that the wrapper class expect an `Any` type: https://github.com/badoo/Reaktive/blob/95645d11f7cc44ce3cb6711b2d637c4de8fcd325/reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/ObservableWrapper.kt#L11

Would it be possible to change it to `Any?` to support nullable types?

The same goes for all wrappers:
ObservableWrapper, SingleWrapper, MaybeWrapper, CompletableWrapper

Is there anything that prevents this functionality?

**Comment by arkivanov** [comment]
Hello @endanke , this was an explicit design decision (see #452). This is due to how nullable generics are exported to Swift via Obj-C. They are always nullable in Swift, regardless off the constraints specified in Kotlin. 

Given the class `class Wrapper<T>` and the function `fun foo(): Wrapper<String>`, it will be nullable in Swift.

So we decided to make this case convenient and compile time safe. You can introduce your own `Optional` type and expose a wrapper of this type. Or you can introduce your own `NullableObservableWrapper<out T>`.

**Comment by endanke** [comment]
@arkivanov Thanks for the clarification!

I think the `NullableObservableWrapper<out T>`  based solution sounds the cleanest, but as I see I would need some internal annotations to do it, so I would probably need to make a fork. If it's possible, it would be nice to have a way to create it as a simple subclass or extension.

Anyway I can deal with my case without nullable types so you can close this issue!

**Comment by arkivanov** [comment]
@endanke As far as I see you don't have to deal with any internal annotations. You can use the following snippet:

```kotlin
import com.badoo.reaktive.annotations.UseReturnValue
import com.badoo.reaktive.disposable.Disposable
import com.badoo.reaktive.observable.Observable
import com.badoo.reaktive.observable.subscribe as subscribeRx

open class NullableObservableWrapper<out T>(inner: Observable<T>) : Observable<T> by inner {

    @UseReturnValue
    fun subscribe(
        isThreadLocal: Boolean = false,
        onSubscribe: ((Disposable) -> Unit)? = null,
        onError: ((Throwable) -> Unit)? = null,
        onComplete: (() -> Unit)? = null,
        onNext: ((T) -> Unit)? = null
    ): Disposable =
        subscribeRx(
            isThreadLocal = isThreadLocal,
            onSubscribe = onSubscribe,
            onError = onError,
            onComplete = onComplete,
            onNext = onNext
        )

    @UseReturnValue
    fun subscribe(): Disposable = subscribeRx()

    @UseReturnValue
    fun subscribe(
        isThreadLocal: Boolean = false,
        onNext: (T) -> Unit
    ): Disposable =
        subscribeRx(
            isThreadLocal = isThreadLocal,
            onNext = onNext
        )

    @UseReturnValue
    fun subscribe(
        isThreadLocal: Boolean = false,
        onComplete: () -> Unit,
        onNext: (T) -> Unit
    ): Disposable =
        subscribeRx(
            isThreadLocal = isThreadLocal,
            onComplete = onComplete,
            onNext = onNext
        )

    @UseReturnValue
    fun subscribe(
        isThreadLocal: Boolean = false,
        onError: (Throwable) -> Unit,
        onComplete: () -> Unit,
        onNext: (T) -> Unit
    ): Disposable =
        subscribeRx(
            isThreadLocal = isThreadLocal,
            onError = onError,
            onComplete = onComplete,
            onNext = onNext
        )
}
```
