### ISSUE TITLE
[2.0.0] API improvements and other fixes

### ISSUE THREAD

**Issue by arkivanov** [badoo/Reaktive#620]
There are some APIs that can be improved/simplified. This issue is to collect all the cases. This is also a good place to raise and discuss any proposals or concerns.

- [x]  `flatMap` - add default value for the `maxConcurrency` argument, remove `flatMap` variants without the `maxConcurrency` argument
- [x]  `flatMap` with `resultSelector` - reorder arguments in the following way: `resultSelector`, `maxConcurrency`, `mapper`
- [x]  `observableInterval` - put `startDelayMillis` after `periodMillis` and add default value `startDelayMillis: Long = periodMillis`, remove another `observableInterval` variant
- [x]  `Observable.replay` - add default for `bufferSize` argument, remove the variant without arguments
- [x] `Completable.asMaybe` and `Completable.asObservable` - remove the generic parameter and make the return generic type `Nothing`
- [x] `doOnAfterSuccess` - rename `action` argument to `consumer`
- [x]  remove all deprecated code
- [x]  `repeat(count: Int = -1)` - the argument name should be `times`, for consistency with `retry` and RxJava. The type should be `Long`, and the default value should be `Long.MAX_VALUE`.
- [x]  `repeat` with value `0` should return empty `Observable`, `repeat` with value `1` should subscribe only once, and so on. For consistency with RxJava.
- [x]  `retry(times: Int)` - the argument type should be `Long`, and the default value should be `Long.MAX_VALUE`.
- [x]  `Observable.scan(getSeed, accumulate)` and `Observable.scan(accumulate)`, - the `accumulate` argument should be renamed to `accumulator` for consistency with RxJava.
- [x]  `Observable.throttle` - should accept a `Scheduler` for timings instead of using `Clock` implicitly, for better testing on the client side.
- [x]  Review all `ExperimentalReaktiveApi`, perhaps we can stabilise something.
- [x]  `collect` should have a mutable collection supplier argument, `accumulator` function should return `Unit`.
- [x] Convert all `millis` durations to the new `Duration` API, if it becomes stable
- [ ] ~~Wait for Multiple Receivers to become stable and extract all `subscribeXyz` extensions from `DisposableScope`, and also `T.scope(dispose: (T) -> Unit)`~~ (removed, context receivers will become stable no earlier than Kotlin 2.0)
- [x] Stabilize the Plugins API
- [x] Remove the old memory model support, optimize for the new memory model
- [x] All `limit` arguments in `Observable.buffer` operators should be of type `Int`
- [x] Remove `iosArm32` and `linuxArm32Hfp` targets, as they are deprecated since Kotlin `1.8.20` and will be removed in Kotlin `1.9.20` (see the [blog post](https://blog.jetbrains.com/kotlin/2023/02/update-regarding-kotlin-native-targets/))
- [x] Remove `asRxJavaSingleSource`, etc. 
- [x] Update readme

**Comment by plusmobileapps** [comment]
With the [Duration API](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.time/-duration/) becoming stable in 1.6, is that something that could be added to the reaktive API to improve functions like the `observableInterval()`?

**Comment by arkivanov** [comment]
@plusmobileapps yes, we have this in the task list. I will investigate and provide updates here.

**Comment by galdp** [comment]
Is for 1.6 (#655) threadLocal still required?

**Comment by arkivanov** [comment]
@galdp Yes it is. `threadLocal` is useful for as long as the Kotlin/Native strict memory model is used. If you opt-in to the new relaxed memory model, then you can avoid using `threadLocal`. Also as a side note, it is not quite related to the version of coroutines.

**Comment by arkivanov** [comment]
We should also remove `iosArm32` and `linuxArm32Hfp` targets, as they are deprecated since Kotlin `1.8.20` and will be removed in Kotlin `1.9.20` (see the [blog post](https://blog.jetbrains.com/kotlin/2023/02/update-regarding-kotlin-native-targets/)). Added to the list.
