### ISSUE TITLE
`Iterable<Observable<T>>.combineLatest` always maps the same list instance

### ISSUE THREAD

**Issue by saket** [badoo/Reaktive#625]
The [`Iterable<Observable<T>>.combineLatest`](https://github.com/badoo/Reaktive/blob/86c6ea6bbbb16fbb0ce7bc48156b57485bc189a4/reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/CombineLatest.kt#L13) operator always maps the same list instance and causes mutability issues. A downstream operator like `distinctUntilChanged` will discard any subsequent items thinking they haven't changed yet. 

I'm working this around by using cloning the combined list using:

```diff
- combineLatest { list -> list }
+ combineLatest { list -> list.toList() }
```

**Comment by arkivanov** [comment]
This was a memory optimisation, but looks like I overlooked this use case. I will fix.
