### ISSUE TITLE
Can reaktive catch errors thrown by nested coroutines?

### ISSUE THREAD

**Issue by saket** [badoo/Reaktive#626]
I’m debugging a case where an exception thrown inside a nested coroutine isn’t bubbling up when singleFromCoroutine is used. I think I can try catch all my nested coroutines to solve this, but can reaktive’s coroutines interop help here by using a `CoroutineExceptionHandler` for launching coroutines?

My understanding of error handling in coroutines comes from this article: https://www.lukaslechner.com/why-exception-handling-with-kotlin-coroutines-is-so-hard-and-how-to-successfully-master-it/

**Comment by arkivanov** [comment]
Thanks! I think the error handling can be improved. I will check.

**Comment by arkivanov** [comment]
Closed via #628 and #630
