### ISSUE TITLE
Couroutine interop extension for Single

### ISSUE THREAD

**Issue by saket** [badoo/Reaktive#629]
Will it be possible to add a coroutine interop operator for `Single`? I see that the official interop library has some extensions for RxJava2: https://github.com/Kotlin/kotlinx.coroutines/tree/master/reactive/kotlinx-coroutines-rx2

In the meantime, I'm using `Single#asObservable()#asFlow().collect`. It looks ugly and not even sure if it's correct, but it seems to work. I _think_ `Single#blockingGet()` will also work but I've run into very strange deadlock issues in the past with blockingGet on RxJava so I try to stay away from it.

**Comment by arkivanov** [comment]
There is `coroutines-interop` module. Will it work for you? Check out the readme: https://github.com/badoo/Reaktive#coroutines-interop

**Comment by arkivanov** [comment]
Closing the issue for now. Feel free to reopen if there are any questions.
