### ISSUE TITLE
Support operator buffer(timespan, time-unit)

### ISSUE THREAD

**Issue by evjava** [badoo/Reaktive#634]
Hi! Are there plans to support operator [buffer(timespan, time-unit)](http://reactivex.io/RxJava/3.x/javadoc/io/reactivex/rxjava3/core/Observable.html#buffer-long-java.util.concurrent.TimeUnit-)?

I need it and right now I found workaround: `.asRxJava2Observable().buffer(timespan, unit).asReaktiveObservable()`. This works, but I would like to get rid of the dependency on `rxjava2-interop`.

**Comment by arkivanov** [comment]
@evjava You can try using the existing `window` operator as follows:

```kotlin
window(spanMillis = x, scheduler = y)
    .flatMapSingle { it.toList() }
```

**Comment by evjava** [comment]
Great, it works. Thanks!
