### ISSUE TITLE
Add Support for Defering Subscriptions

### ISSUE THREAD

**Issue by hopeman15** [badoo/Reaktive#654]
It would be great to add support for defering the time of subscription on the streams for example:

```
Completable.defer {
    // code here 
}
```

**Comment by arkivanov** [comment]
@hopeman15 hello, could please elaborate what you mean by "defering the time of subscription"? There is [observableDefer](https://github.com/badoo/Reaktive/blob/master/reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/Defer.kt) function, and similar for other types of sources. There is also [delaySubscription](https://github.com/badoo/Reaktive/blob/master/reaktive/src/commonMain/kotlin/com/badoo/reaktive/observable/DelaySubscription.kt) operator.

**Comment by hopeman15** [comment]
@arkivanov I think you might have pointed me in the right direction. So I was looking for something where one can create streams and defer the subscription like you can in the standard library:

```
Completable.defer {
    // code here 
}
```

So I guess the equivalent would be:

completableDefer {
    // code here 
}

And I guess that `Completable.create { }` -> `completable {  }` ?

**Comment by arkivanov** [comment]
Exactly, that is 1-1 mapping.

**Comment by hopeman15** [comment]
> Exactly, that is 1-1 mapping.

Perfect and thanks 🙌 sorry for opening an unnecessary issue 🙈

**Comment by arkivanov** [comment]
@CherryPerry perhaps this issue can be closed, thanks!
