### ISSUE TITLE
ComputationScheduler getting stuck

### ISSUE THREAD

**Issue by Ucash** [badoo/Reaktive#661]
I've observed a strange behaviour of work executed on computationScheduler. One of my task is time consuming (like 3-4 minutes) and it turns out a couple of other tasks wait for its completion instead of working in parallel. Issue is for sure reproducible on Android and iOS.

I've made some investigation, and noticed that FixedLooperThreadStrategy and FixedExecutorServiceStrategy assigns threads in order without checking if another thread from the pool is currently idle. Shouldn't work queue be shared within whole thread pool?

**Comment by arkivanov** [comment]
Hello and thanks for the question. This behaviour is expected, the `computationScheduler` uses a simple round robin algorithm for picking executors from the pool. This is also aligned with RxJava, see similar [issue](https://github.com/ReactiveX/RxJava/issues/7294). For long running tasks it is advised to use either `newThreadScheduler` or simply `ioScheduler`.

**Comment by Ucash** [comment]
Thank you for answer
