### ISSUE TITLE
Possible problems during upgrade to Kotlin 1.7.0

### ISSUE THREAD

**Issue by atyrin** [badoo/Reaktive#663]
Hey,

I've discovered the issue of upgrading the Reaktive project on the 1.7.0 Kotlin version (on RC). The IDE import and project build may fail with errors about binary incompatibility. For example: 
```
> Task :gradleConfiguration:compileKotlin FAILED
e: /.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-compiler-embeddable/1.7.0-RC-211/f5185a225bcd8d4d47023bae2b76b687aba0d372/kotlin-compiler-embeddable-1.7.0-RC-211.jar!/META-INF/backend-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
```

The problem here is the `org.jetbrains.kotlin:kotlin-compiler-embeddable` dependency inside `gradleConfiguration`. It includes a `1.7.0` version of the artifact to the project. But it conflicts with the version required by the Kotlin 1.5.31 bundled to Gradle wrapper that also depends on `kotlin-compiler-embeddable`. The outdated Kotlin was involved in the process since the module for composite build uses `kotlin-dsl` plugin for configuration. 
All that leads to the incompatible difference in metadata in more than 1 minor version (1.5.1 vs 1.7.1).

Suggested workaround:
* Upgrade Gradle wrapper to 7.5 (currently in RC but maybe after the release of 1.7.0 will be available in Stable). It will include 1.6.21 Kotlin. 
* Keep `kotlin-compiler-embeddable` dependency with the 1.6.20 version.

No action is required right now, just to be aware.
Thanks for the library!

**Comment by arkivanov** [comment]
Thanks for the hint! I'm wondering what's your use case of updating Reaktive manually?

**Comment by atyrin** [comment]
Just a part of internal pre-release checks inside the Kotlin team.
