### ISSUE TITLE
BehaviorRelay constructor?

### ISSUE THREAD

**Issue by rickytribbia** [badoo/Reaktive#680]
Hi, how can we construct a BehaviorRelay? 
If have we understood well the constructor of this class isn't yet implemented, are we right?

**Comment by CherryPerry** [comment]
Use `BehaviorSubject` function.

```kotlin
fun test() {
    val relay: BehaviorRelay<Int> = BehaviorSubject(initialValue = 0)
    relay.onNext(1)
}
```

**Comment by arkivanov** [comment]
As a side note, `BahviorSubject` interface extends `BehaviorRelay` interface. `BehaviorRelay` interface can be used to hide `onComplete` and `onError` methods and `Subject#status` property.

**Comment by rickytribbia** [comment]
Thank you!
