### ISSUE TITLE
The binary version of its metadata is 1.8.0 expected version is 1.6.0 . How do i fix this in jetpack compose?

### ISSUE THREAD

**Issue by MuindiStephen** [badoo/Reaktive#728]

**Comment by arkivanov** [comment]
It doesn't look related to Reaktive. Most likely you have are using Kotlin 1.8.0 and still have some dependencies compiled again Kotlin 1.6.x. The most common case on my experience is outdated Android Gradle Plugin, or Detekt.

**Comment by MuindiStephen** [comment]
> It doesn't look related to Reaktive. Most likely you have are using Kotlin 1.8.0 and still have some dependencies compiled again Kotlin 1.6.x. The most common case on my experience is outdated Android Gradle Plugin, or Detekt.

- @arkivanov Wow! I got to fix it
- I added build gradle plugin dependency with version 1.8.0

**Comment by user624-47** [comment]
> > It doesn't look related to Reaktive. Most likely you have are using Kotlin 1.8.0 and still have some dependencies compiled again Kotlin 1.6.x. The most common case on my experience is outdated Android Gradle Plugin, or Detekt.
> 
> * @arkivanov Wow! I got to fix it
> * I added build gradle plugin dependency with version 1.8.0

Please can you share how you fixed it?
