### ISSUE TITLE
After updating to version 2.0.0 cdass com.badoo.reaktive.utils.lock.Condition is not available

### ISSUE THREAD

**Issue by lemkoleg** [badoo/Reaktive#768]
After updating to version 2.0.1 cdass com.badoo.reaktive.utils.lock.Condition is not available. Will it not be supported?

**Comment by arkivanov** [comment]
The `utils` module has been renamed to `utils-internal` and its content is now considered internal (not part of the public API). `Condition` was replaced to [ConditionLock](https://github.com/badoo/Reaktive/blob/master/utils-internal/src/commonMain/kotlin/com/badoo/reaktive/utils/lock/ConditionLock.kt) for performance reasons. Feel free to copy `Condition` to your project from [the old version](https://github.com/badoo/Reaktive/tree/b43ba007626003e19cec93cb79b64df9d824154d/utils-internal/src/commonMain/kotlin/com/badoo/reaktive/utils/lock). You can also try using `ConditionLock` at your own risk, but this is not recommended.
