### ISSUE TITLE
Please implement the retryWhen operator

### ISSUE THREAD

**Issue by thearaks** [badoo/Reaktive#780]
The `retryWhen` operator is very useful for handling errors and retries with delays but I think it's not been implemented yet in Reaktive.

This is the official documentation on this operator: [ReactiveX - Retry operator](https://reactivex.io/documentation/operators/retry.html)

It would be awesome to have it added to the library!
Thank you!

**Comment by arkivanov** [comment]
Yeah, I think I could add it.

**Comment by arkivanov** [comment]
Available since version [2.3.0](https://github.com/badoo/Reaktive/releases/tag/2.3.0).
